import Head from "next/head";
import { Card } from "@/components/Card/Card";
import { getLayoutCardPages } from "@/layouts/LayoutCardPages";
import { IData } from "@/layouts/LayoutCardPages/types";
import { Pagination } from "@/components/Pagination/Pagination";
import { useGetCurrentData } from "@/layouts/LayoutCardPages/hooks/useGetCurrentData";

export default function Home({ count }: IData) {
  const data = useGetCurrentData("games");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card data={data} />
      {count > 20 && (
        <div className={"layoutCardPages__Pagination"}>
          <Pagination count={count} />
        </div>
      )}
    </>
  );
}

Home.getLayout = getLayoutCardPages;

export async function getServerSideProps(context) {
  // check page=44283 after deploy
  const res = await fetch(
    `https://api.rawg.io/api/games?key=${
      process.env.API_KEY
    }&page_size=20&page=${context.query.page || 1}`
  );
  const data = await res.json();

  return {
    props: {
      data: data?.results,
      count: data.count,
    },
  };
}
